version: "3.8"
services:
  mail:
    build:
      context: ./docker/
    container_name: mail
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80
    networks:
      - internal


networks:
  internal:
